### ISSUE TITLE
Static on separated images

### ISSUE THREAD

**Issue by moinism** [stil/gif-endec#1]
It is creating some really distorted images on few gifs.
Try converting this one:
![fresh](https://cloud.githubusercontent.com/assets/2242528/6199176/c393318c-b455-11e4-8bb1-2ad58e874a41.gif)

While if we convert it using https://github.com/Sybio/GifFrameExtractor than there is no problem.

**Comment by stil** [comment]
In fact, those frames include transparency:
![frame](https://cloud.githubusercontent.com/assets/714004/6199445/118a6570-b444-11e4-8af6-e7d3163fa929.PNG)

Usually first frame "looks normal". You need to overlay this first frame with following semi-transparent frames. This method of animation saves file size.

Your original GIF image is:
- 0,98 Mb (bytes: 1 037 972)

But if you saved it without transparency, it would be
- 1.13 Mb (bytes: 1 188 778) ~15% bigger.

However I'll fix it, by setting it default to decode such GIFs, so separate frames look "normal".

Edit: In the animation below you can see transition between first and second frame. (2nd one is overlayed over first frame).

![fade](https://cloud.githubusercontent.com/assets/714004/6199626/45a4a7b0-b450-11e4-80fc-4d052be1ee85.gif)

**Comment by stil** [comment]
Does it https://github.com/stil/gif-endec/blob/master/README.md#render-animated-gifs-frames-with-transparency solve your problem?

**Comment by moinism** [comment]
Yep, now it works on almost all the gifs with transparency. 
Just this one is still same as previous results:

![iphone](https://cloud.githubusercontent.com/assets/2242528/6214953/53b4cfb8-b61e-11e4-8fea-efdcfc890828.gif)

First three frames are 'normal' and then same thing. Try it please.
Also, your script uses tremendously less amount of memory and time as compared to the other script.
P.S: you rock! :+1:

**Comment by stil** [comment]
You're right, this GIF has frames with different sizes. I added few commits which should solve this issue. Check it out now.

**Comment by moinism** [comment]
Awesome, its working great now. Really Nice work.
