### ISSUE TITLE
Corrupt file if local color tables

### ISSUE THREAD

**Issue by chrisgraham** [stil/gif-endec#4]
If you load up an animated gif, then substitute the stream of each frame with that of an altered gif file, then re-save, it switches to local color tables (as expected), but it comes out corrupt. Something is wrong about the file format implementation I think, but I don't have time to trace through it.
If I re-save with the same frame streams it works okay. If I hack the code to disable local color table saving it saves okay but with corrupt palette (as expected).

**Comment by stil** [comment]
Please provide sample image that causes crash. I will reopen this issue then.
